//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramareAC.Web.ServiceReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string current_paramsField;
        
        private string current_request_nameField;
        
        private string nested_exceptionField;
        
        private DataServiceFaultSource_data_service source_data_serviceField;
        
        private string ds_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string current_params {
            get {
                return this.current_paramsField;
            }
            set {
                this.current_paramsField = value;
                this.RaisePropertyChanged("current_params");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string current_request_name {
            get {
                return this.current_request_nameField;
            }
            set {
                this.current_request_nameField = value;
                this.RaisePropertyChanged("current_request_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nested_exception {
            get {
                return this.nested_exceptionField;
            }
            set {
                this.nested_exceptionField = value;
                this.RaisePropertyChanged("nested_exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DataServiceFaultSource_data_service source_data_service {
            get {
                return this.source_data_serviceField;
            }
            set {
                this.source_data_serviceField = value;
                this.RaisePropertyChanged("source_data_service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ds_code {
            get {
                return this.ds_codeField;
            }
            set {
                this.ds_codeField = value;
                this.RaisePropertyChanged("ds_code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFaultSource_data_service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string locationField;
        
        private string default_namespaceField;
        
        private string descriptionField;
        
        private string data_service_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string default_namespace {
            get {
                return this.default_namespaceField;
            }
            set {
                this.default_namespaceField = value;
                this.RaisePropertyChanged("default_namespace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string data_service_name {
            get {
                return this.data_service_nameField;
            }
            set {
                this.data_service_nameField = value;
                this.RaisePropertyChanged("data_service_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.wso2.org/dataservice", ConfigurationName="ServiceReference.WSO2_package_017ACPortType")]
    public interface WSO2_package_017ACPortType {
        
        // CODEGEN: Generating message contract since the wrapper name (Group_proc_test) of message proc_testResponse does not match the default value (proc_test)
        [System.ServiceModel.OperationContractAttribute(Action="urn:proc_test", ReplyAction="urn:proc_testResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProgramareAC.Web.ServiceReference.DataServiceFault), Action="urn:proc_testDataServiceFault", Name="DataServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProgramareAC.Web.ServiceReference.proc_testResponse proc_test(ProgramareAC.Web.ServiceReference.proc_testRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:proc_test", ReplyAction="urn:proc_testResponse")]
        System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.proc_testResponse> proc_testAsync(ProgramareAC.Web.ServiceReference.proc_testRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (Group_getstatus) of message Get_StatusResponse does not match the default value (Get_Status)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Get_Status", ReplyAction="urn:Get_StatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProgramareAC.Web.ServiceReference.DataServiceFault), Action="urn:Get_StatusDataServiceFault", Name="DataServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProgramareAC.Web.ServiceReference.Get_StatusResponse Get_Status(ProgramareAC.Web.ServiceReference.Get_StatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Get_Status", ReplyAction="urn:Get_StatusResponse")]
        System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.Get_StatusResponse> Get_StatusAsync(ProgramareAC.Web.ServiceReference.Get_StatusRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (Group_get_FreeTime) of message get_FreeTimeResponse does not match the default value (get_FreeTime)
        [System.ServiceModel.OperationContractAttribute(Action="urn:get_FreeTime", ReplyAction="urn:get_FreeTimeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProgramareAC.Web.ServiceReference.DataServiceFault), Action="urn:get_FreeTimeDataServiceFault", Name="DataServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProgramareAC.Web.ServiceReference.get_FreeTimeResponse get_FreeTime(ProgramareAC.Web.ServiceReference.get_FreeTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:get_FreeTime", ReplyAction="urn:get_FreeTimeResponse")]
        System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.get_FreeTimeResponse> get_FreeTimeAsync(ProgramareAC.Web.ServiceReference.get_FreeTimeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (Rez) of message set_TimeResponse does not match the default value (set_Time)
        [System.ServiceModel.OperationContractAttribute(Action="urn:set_Time", ReplyAction="urn:set_TimeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProgramareAC.Web.ServiceReference.DataServiceFault), Action="urn:set_TimeDataServiceFault", Name="DataServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProgramareAC.Web.ServiceReference.set_TimeResponse set_Time(ProgramareAC.Web.ServiceReference.set_TimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:set_Time", ReplyAction="urn:set_TimeResponse")]
        System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.set_TimeResponse> set_TimeAsync(ProgramareAC.Web.ServiceReference.set_TimeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (Group_get_RN) of message get_RNResponse does not match the default value (get_RN)
        [System.ServiceModel.OperationContractAttribute(Action="urn:get_RN", ReplyAction="urn:get_RNResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProgramareAC.Web.ServiceReference.DataServiceFault), Action="urn:get_RNDataServiceFault", Name="DataServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProgramareAC.Web.ServiceReference.get_RNResponse get_RN(ProgramareAC.Web.ServiceReference.get_RNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:get_RN", ReplyAction="urn:get_RNResponse")]
        System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.get_RNResponse> get_RNAsync(ProgramareAC.Web.ServiceReference.get_RNRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (Group_get_Serv) of message get_ServResponse does not match the default value (get_Serv)
        [System.ServiceModel.OperationContractAttribute(Action="urn:get_Serv", ReplyAction="urn:get_ServResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProgramareAC.Web.ServiceReference.DataServiceFault), Action="urn:get_ServDataServiceFault", Name="DataServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProgramareAC.Web.ServiceReference.get_ServResponse get_Serv(ProgramareAC.Web.ServiceReference.get_ServRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:get_Serv", ReplyAction="urn:get_ServResponse")]
        System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.get_ServResponse> get_ServAsync(ProgramareAC.Web.ServiceReference.get_ServRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="proc_test", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class proc_testRequest {
        
        public proc_testRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Group_proc_test", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class proc_testResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string p1;
        
        public proc_testResponse() {
        }
        
        public proc_testResponse(string p1) {
            this.p1 = p1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wso2.org/dataservice")]
    public partial class Row : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pDescrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string pDescr {
            get {
                return this.pDescrField;
            }
            set {
                this.pDescrField = value;
                this.RaisePropertyChanged("pDescr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_Status", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class Get_StatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pCerereId;
        
        public Get_StatusRequest() {
        }
        
        public Get_StatusRequest(System.Nullable<int> pCerereId) {
            this.pCerereId = pCerereId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Group_getstatus", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class Get_StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Row")]
        public ProgramareAC.Web.ServiceReference.Row[] Row;
        
        public Get_StatusResponse() {
        }
        
        public Get_StatusResponse(ProgramareAC.Web.ServiceReference.Row[] Row) {
            this.Row = Row;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wso2.org/dataservice")]
    public partial class Row2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orar_idField;
        
        private string orar_dayField;
        
        private string orar_timeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string orar_id {
            get {
                return this.orar_idField;
            }
            set {
                this.orar_idField = value;
                this.RaisePropertyChanged("orar_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string orar_day {
            get {
                return this.orar_dayField;
            }
            set {
                this.orar_dayField = value;
                this.RaisePropertyChanged("orar_day");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string orar_time {
            get {
                return this.orar_timeField;
            }
            set {
                this.orar_timeField = value;
                this.RaisePropertyChanged("orar_time");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_FreeTime", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class get_FreeTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Branch_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Serv_rf;
        
        public get_FreeTimeRequest() {
        }
        
        public get_FreeTimeRequest(string Branch_code, System.Nullable<decimal> Serv_rf) {
            this.Branch_code = Branch_code;
            this.Serv_rf = Serv_rf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Group_get_FreeTime", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class get_FreeTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Row")]
        public ProgramareAC.Web.ServiceReference.Row2[] Row;
        
        public get_FreeTimeResponse() {
        }
        
        public get_FreeTimeResponse(ProgramareAC.Web.ServiceReference.Row2[] Row) {
            this.Row = Row;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wso2.org/dataservice")]
    public partial class Row3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rezult_TextField;
        
        private System.Nullable<decimal> errorField;
        
        private string pCERERE_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Rezult_Text {
            get {
                return this.rezult_TextField;
            }
            set {
                this.rezult_TextField = value;
                this.RaisePropertyChanged("Rezult_Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=2)]
        public string pCERERE_ID {
            get {
                return this.pCERERE_IDField;
            }
            set {
                this.pCERERE_IDField = value;
                this.RaisePropertyChanged("pCERERE_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="set_Time", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class set_TimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDNP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BirthDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Orar_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Serv_rf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> RN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pTel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pTema;
        
        public set_TimeRequest() {
        }
        
        public set_TimeRequest(string IDNP, string LastName, string FirstName, string BirthDate, System.Nullable<decimal> Orar_ID, System.Nullable<decimal> Serv_rf, System.Nullable<decimal> RN, string pEmail, string pTel, string pTema) {
            this.IDNP = IDNP;
            this.LastName = LastName;
            this.FirstName = FirstName;
            this.BirthDate = BirthDate;
            this.Orar_ID = Orar_ID;
            this.Serv_rf = Serv_rf;
            this.RN = RN;
            this.pEmail = pEmail;
            this.pTel = pTel;
            this.pTema = pTema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Rez", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class set_TimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Row")]
        public ProgramareAC.Web.ServiceReference.Row3[] Row;
        
        public set_TimeResponse() {
        }
        
        public set_TimeResponse(ProgramareAC.Web.ServiceReference.Row3[] Row) {
            this.Row = Row;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wso2.org/dataservice")]
    public partial class Row4 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> rnField;
        
        private string nAMERField;
        
        private string aDRESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> RN {
            get {
                return this.rnField;
            }
            set {
                this.rnField = value;
                this.RaisePropertyChanged("RN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string NAMER {
            get {
                return this.nAMERField;
            }
            set {
                this.nAMERField = value;
                this.RaisePropertyChanged("NAMER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ADRES {
            get {
                return this.aDRESField;
            }
            set {
                this.aDRESField = value;
                this.RaisePropertyChanged("ADRES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_RN", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class get_RNRequest {
        
        public get_RNRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Group_get_RN", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class get_RNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Row")]
        public ProgramareAC.Web.ServiceReference.Row4[] Row;
        
        public get_RNResponse() {
        }
        
        public get_RNResponse(ProgramareAC.Web.ServiceReference.Row4[] Row) {
            this.Row = Row;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wso2.org/dataservice")]
    public partial class Row5 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sERV_IDField;
        
        private string sERV_NAME_ROField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SERV_ID {
            get {
                return this.sERV_IDField;
            }
            set {
                this.sERV_IDField = value;
                this.RaisePropertyChanged("SERV_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string SERV_NAME_RO {
            get {
                return this.sERV_NAME_ROField;
            }
            set {
                this.sERV_NAME_ROField = value;
                this.RaisePropertyChanged("SERV_NAME_RO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_Serv", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class get_ServRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> RN;
        
        public get_ServRequest() {
        }
        
        public get_ServRequest(System.Nullable<decimal> RN) {
            this.RN = RN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Group_get_Serv", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class get_ServResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Row")]
        public ProgramareAC.Web.ServiceReference.Row5[] Row;
        
        public get_ServResponse() {
        }
        
        public get_ServResponse(ProgramareAC.Web.ServiceReference.Row5[] Row) {
            this.Row = Row;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSO2_package_017ACPortTypeChannel : ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSO2_package_017ACPortTypeClient : System.ServiceModel.ClientBase<ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType>, ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType {
        
        public WSO2_package_017ACPortTypeClient() {
        }
        
        public WSO2_package_017ACPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSO2_package_017ACPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSO2_package_017ACPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSO2_package_017ACPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramareAC.Web.ServiceReference.proc_testResponse ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType.proc_test(ProgramareAC.Web.ServiceReference.proc_testRequest request) {
            return base.Channel.proc_test(request);
        }
        
        public string proc_test() {
            ProgramareAC.Web.ServiceReference.proc_testRequest inValue = new ProgramareAC.Web.ServiceReference.proc_testRequest();
            ProgramareAC.Web.ServiceReference.proc_testResponse retVal = ((ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType)(this)).proc_test(inValue);
            return retVal.p1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.proc_testResponse> ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType.proc_testAsync(ProgramareAC.Web.ServiceReference.proc_testRequest request) {
            return base.Channel.proc_testAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.proc_testResponse> proc_testAsync() {
            ProgramareAC.Web.ServiceReference.proc_testRequest inValue = new ProgramareAC.Web.ServiceReference.proc_testRequest();
            return ((ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType)(this)).proc_testAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramareAC.Web.ServiceReference.Get_StatusResponse ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType.Get_Status(ProgramareAC.Web.ServiceReference.Get_StatusRequest request) {
            return base.Channel.Get_Status(request);
        }
        
        public ProgramareAC.Web.ServiceReference.Row[] Get_Status(System.Nullable<int> pCerereId) {
            ProgramareAC.Web.ServiceReference.Get_StatusRequest inValue = new ProgramareAC.Web.ServiceReference.Get_StatusRequest();
            inValue.pCerereId = pCerereId;
            ProgramareAC.Web.ServiceReference.Get_StatusResponse retVal = ((ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType)(this)).Get_Status(inValue);
            return retVal.Row;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.Get_StatusResponse> ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType.Get_StatusAsync(ProgramareAC.Web.ServiceReference.Get_StatusRequest request) {
            return base.Channel.Get_StatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.Get_StatusResponse> Get_StatusAsync(System.Nullable<int> pCerereId) {
            ProgramareAC.Web.ServiceReference.Get_StatusRequest inValue = new ProgramareAC.Web.ServiceReference.Get_StatusRequest();
            inValue.pCerereId = pCerereId;
            return ((ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType)(this)).Get_StatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramareAC.Web.ServiceReference.get_FreeTimeResponse ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType.get_FreeTime(ProgramareAC.Web.ServiceReference.get_FreeTimeRequest request) {
            return base.Channel.get_FreeTime(request);
        }
        
        public ProgramareAC.Web.ServiceReference.Row2[] get_FreeTime(string Branch_code, System.Nullable<decimal> Serv_rf) {
            ProgramareAC.Web.ServiceReference.get_FreeTimeRequest inValue = new ProgramareAC.Web.ServiceReference.get_FreeTimeRequest();
            inValue.Branch_code = Branch_code;
            inValue.Serv_rf = Serv_rf;
            ProgramareAC.Web.ServiceReference.get_FreeTimeResponse retVal = ((ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType)(this)).get_FreeTime(inValue);
            return retVal.Row;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.get_FreeTimeResponse> ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType.get_FreeTimeAsync(ProgramareAC.Web.ServiceReference.get_FreeTimeRequest request) {
            return base.Channel.get_FreeTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.get_FreeTimeResponse> get_FreeTimeAsync(string Branch_code, System.Nullable<decimal> Serv_rf) {
            ProgramareAC.Web.ServiceReference.get_FreeTimeRequest inValue = new ProgramareAC.Web.ServiceReference.get_FreeTimeRequest();
            inValue.Branch_code = Branch_code;
            inValue.Serv_rf = Serv_rf;
            return ((ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType)(this)).get_FreeTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramareAC.Web.ServiceReference.set_TimeResponse ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType.set_Time(ProgramareAC.Web.ServiceReference.set_TimeRequest request) {
            return base.Channel.set_Time(request);
        }
        
        public ProgramareAC.Web.ServiceReference.Row3[] set_Time(string IDNP, string LastName, string FirstName, string BirthDate, System.Nullable<decimal> Orar_ID, System.Nullable<decimal> Serv_rf, System.Nullable<decimal> RN, string pEmail, string pTel, string pTema) {
            ProgramareAC.Web.ServiceReference.set_TimeRequest inValue = new ProgramareAC.Web.ServiceReference.set_TimeRequest();
            inValue.IDNP = IDNP;
            inValue.LastName = LastName;
            inValue.FirstName = FirstName;
            inValue.BirthDate = BirthDate;
            inValue.Orar_ID = Orar_ID;
            inValue.Serv_rf = Serv_rf;
            inValue.RN = RN;
            inValue.pEmail = pEmail;
            inValue.pTel = pTel;
            inValue.pTema = pTema;
            ProgramareAC.Web.ServiceReference.set_TimeResponse retVal = ((ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType)(this)).set_Time(inValue);
            return retVal.Row;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.set_TimeResponse> ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType.set_TimeAsync(ProgramareAC.Web.ServiceReference.set_TimeRequest request) {
            return base.Channel.set_TimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.set_TimeResponse> set_TimeAsync(string IDNP, string LastName, string FirstName, string BirthDate, System.Nullable<decimal> Orar_ID, System.Nullable<decimal> Serv_rf, System.Nullable<decimal> RN, string pEmail, string pTel, string pTema) {
            ProgramareAC.Web.ServiceReference.set_TimeRequest inValue = new ProgramareAC.Web.ServiceReference.set_TimeRequest();
            inValue.IDNP = IDNP;
            inValue.LastName = LastName;
            inValue.FirstName = FirstName;
            inValue.BirthDate = BirthDate;
            inValue.Orar_ID = Orar_ID;
            inValue.Serv_rf = Serv_rf;
            inValue.RN = RN;
            inValue.pEmail = pEmail;
            inValue.pTel = pTel;
            inValue.pTema = pTema;
            return ((ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType)(this)).set_TimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramareAC.Web.ServiceReference.get_RNResponse ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType.get_RN(ProgramareAC.Web.ServiceReference.get_RNRequest request) {
            return base.Channel.get_RN(request);
        }
        
        public ProgramareAC.Web.ServiceReference.Row4[] get_RN() {
            ProgramareAC.Web.ServiceReference.get_RNRequest inValue = new ProgramareAC.Web.ServiceReference.get_RNRequest();
            ProgramareAC.Web.ServiceReference.get_RNResponse retVal = ((ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType)(this)).get_RN(inValue);
            return retVal.Row;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.get_RNResponse> ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType.get_RNAsync(ProgramareAC.Web.ServiceReference.get_RNRequest request) {
            return base.Channel.get_RNAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.get_RNResponse> get_RNAsync() {
            ProgramareAC.Web.ServiceReference.get_RNRequest inValue = new ProgramareAC.Web.ServiceReference.get_RNRequest();
            return ((ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType)(this)).get_RNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramareAC.Web.ServiceReference.get_ServResponse ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType.get_Serv(ProgramareAC.Web.ServiceReference.get_ServRequest request) {
            return base.Channel.get_Serv(request);
        }
        
        public ProgramareAC.Web.ServiceReference.Row5[] get_Serv(System.Nullable<decimal> RN) {
            ProgramareAC.Web.ServiceReference.get_ServRequest inValue = new ProgramareAC.Web.ServiceReference.get_ServRequest();
            inValue.RN = RN;
            ProgramareAC.Web.ServiceReference.get_ServResponse retVal = ((ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType)(this)).get_Serv(inValue);
            return retVal.Row;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.get_ServResponse> ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType.get_ServAsync(ProgramareAC.Web.ServiceReference.get_ServRequest request) {
            return base.Channel.get_ServAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramareAC.Web.ServiceReference.get_ServResponse> get_ServAsync(System.Nullable<decimal> RN) {
            ProgramareAC.Web.ServiceReference.get_ServRequest inValue = new ProgramareAC.Web.ServiceReference.get_ServRequest();
            inValue.RN = RN;
            return ((ProgramareAC.Web.ServiceReference.WSO2_package_017ACPortType)(this)).get_ServAsync(inValue);
        }
    }
}
